// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pktpwdpogbkoccmkkodi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdHB3ZHBvZ2Jrb2NjbWtrb2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjY3OTIsImV4cCI6MjA2NzA0Mjc5Mn0.muwiFUq2TxXuWBO19h6PKY_sJyvNVxh2Jry4xeoS8Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});